removed duplicated records and  fixed those distinct genes associated with same ensembl ID from the file included in  PR #24
collaborativebioinformatics/VariantSurvival pull request #26
Opened 2023-07-29 02:44 UTC by msarrias

2023-07-29 15:26 UTC, HibaBenAribi commented
1. there is errro in description file please correct the authors information section as follow :
Authors: c(
          person("Ahmad", "Al khleifat", , "ahmad.al_khleifat@kcl.ac.uk", role = c("aut"), comment = c(ORCID = "0000-0002-7406-9831")),
          person("Thomas", "Krannich", , "krannichT@rki.de", role = c("aut"), comment = c(ORCID = "0000-0002-5525-1849")),
          person("Hiba", "Ben Aribi", , "benaribi.hiba@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-9547-8725")),
          person("Marina", "Herrera Sarrias", , "marina.sarrias@math.su.se", role = c("aut", "cre")),
          person("Moustafa", "Shokrof", , "meshokrof@ucdavis.edu", role = c("aut"), comment = c(ORCID = "0000-0003-1040-2145")))

2. The cox tab is not functional it keeps close up

2023-07-29 23:11 UTC, msarrias commented
> 2\. The cox tab is not functional, it keeps closing

Can you be more specific?, i.e., What's the error message you get in RStudio? how are you installing and running the app?

2023-08-15 11:34 UTC, HibaBenAribi commented
> > 2. The cox tab is not functional, it keeps closing
> 
> Can you be more specific?, i.e., What's the error message you get in RStudio? how are you installing and running the app?

I do not get any specific error in the terminal. However, no matter which factor I choose the app closes.
Suggestion: add a default selection based on the metadata columns selected in tab1.

2023-09-28 16:43 UTC, msarrias commented
> > > 2. The cox tab is not functional, it keeps closing
> > 
> > 
> > Can you be more specific?, i.e., What's the error message you get in RStudio? how are you installing and running the app?
> 
> I do not get any specific error in the terminal. However, no matter which factor I choose the app closes. Suggestion: add a default selection based on the metadata columns selected in tab1.

you might want to re-install the survival package.

2023-09-30 09:41 UTC, Krannich479 commented
@msarrias, I agree with you about the p-values and the general purpose of this PR. However, imho we need to chat about some details of this PR as well as automated security mechanisms (CI) for this repository. At the moment I cannot keep up with the quantity of code changes and guarantee code integrity and safety. 
(getting back to you on slack?)

2023-12-24 16:19 UTC, msarrias commented
@Krannich479 

If you run (without changing working directories)
```
>devtools::install_github("collaborativebioinformatics/VariantSurvival/VariantSurvival_package@msarrias", force = TRUE)
>VariantSurvival::VariantSurvival(demo = TRUE)
```

Should work!

2024-01-18 13:37 UTC, Krannich479 commented on VariantSurvival_package/R/VariantSurvival.R
No code review in full detail but tested functional ✅

2024-01-18 13:38 UTC, Krannich479 approved these changes

2024-01-19 11:39 UTC, Krannich479 commented on VariantSurvival_package/R/VariantSurvival.R
> +                survminer::surv_summary(
👍

2024-01-19 11:40 UTC, Krannich479 commented on VariantSurvival_package/R/VariantSurvival.R
> +                survminer::surv_summary(
👍

2024-01-19 11:41 UTC, Krannich479 commented
✅ life table error solved with commit b9284f48294ca594c92a539c85c1d165d77d0ae9

2024-01-19 11:49 UTC, Krannich479 commented
@msarrias :
From the _Gene\_ID_ list of counts per gene, I cannot find all the genes in the _Gene of interest_ panel. For instance:
Selecting **Charcot-Marie-Tooth** the top 5 hits are:

1. SETX | 43
2. ALS2 | 31
3. NEFH | 25
4. VAPB | 18
5. FIG4 | 16

However, I cannot find the top 2 and top 4 hit ("ALS2" and "VAPB") in the _Gene of interest_ selection panel.

2024-01-20 13:44 UTC, msarrias commented
> @msarrias : From the _Gene_ID_ list of counts per gene, I cannot find all the genes in the _Gene of interest_ panel. For instance: Selecting **Charcot-Marie-Tooth** the top 5 hits are:
> 
> 1. SETX | 43
> 2. ALS2 | 31
> 3. NEFH | 25
> 4. VAPB | 18
> 5. FIG4 | 16
> 
> However, I cannot find the top 2 and top 4 hit ("ALS2" and "VAPB") in the _Gene of interest_ selection panel.

In the `disease_gene` file, those genes are not listed as associated with the disease you mentioned. This is because either they are indeed not related to the disease (but still carry svs) or the genes are missing from the disease file. I can't find them in the biomarker table so I don't think they are related to the disease.

2024-01-21 15:49 UTC, Krannich479 requested changes

2024-01-21 15:49 UTC, Krannich479 commented on VariantSurvival_package/R/VariantSurvival.R
> +                title = span("Null Model",
_span()_ requires scope (found multiple ones for function _span_, don't know which one is required here)

2024-01-21 15:49 UTC, Krannich479 commented on VariantSurvival_package/R/VariantSurvival.R
> +                title = span("Null Model",
sometimes _htmltools::_, sometimes _shiny::_

2024-01-21 15:49 UTC, Krannich479 commented on VariantSurvival_package/R/VariantSurvival.R
> +                title = span("Multiple Model",
span() requires scope (found multiple ones for function span, don't know which one is required here)

2024-02-02 14:08 UTC, Krannich479 approved these changes

2024-03-06 14:01 UTC, merged